### ISSUE TITLE
Recurso ProcessTaskInbox , ProcessReports y ProcessMonitor genera exepción al procesar JSP editRessource.jsp

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBP#24]
2017-08-22 16:27:28,651 ERROR - Error to process JSP.../swbadmin/jsp/editResource.jsp
org.apache.jasper.JasperException: An exception occurred processing JSP page /swbadmin/jsp/editResource.jsp at line 30

27:
28:             SWBHttpServletResponseWrapper resp=new SWBHttpServletResponseWrapper(response);
29:
30:             sem.render(request, resp, req);
31:
32:             out.print(resp.toString());
33:

Stacktrace:
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:588)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516)
        at org.semanticwb.portal.resources.JSPResource.doView(JSPResource.java:91)
        at org.semanticwb.portal.api.GenericResource.processRequest(GenericResource.java:141)
        at org.semanticwb.portal.api.GenericResource.render(GenericResource.java:124)
        at org.semanticwb.portal.api.SWBResourceWindowRender.render(SWBResourceWindowRender.java:80)
        at org.semanticwb.portal.api.SWBResourceTraceMgr.renderTraced(SWBResourceTraceMgr.java:167)
        at org.semanticwb.portal.TemplateImp.build(TemplateImp.java:1098)
        at org.semanticwb.portal.TemplateImp.build(TemplateImp.java:934)
        at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.java:453)
        at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.java:101)
        at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:392)
        at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:319)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1368)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.semanticwb.portal.SWBFormMgr.init(SWBFormMgr.java:179)
        at org.semanticwb.portal.SWBFormMgr.<init>(SWBFormMgr.java:143)
        at org.semanticwb.process.resources.taskinbox.UserTaskInboxResource.doAdmin(UserTaskInboxResource.java:550)
        at org.semanticwb.portal.api.GenericResource.processRequest(GenericResource.java:150)
        at org.semanticwb.process.resources.taskinbox.UserTaskInboxResource.processRequest(UserTaskInboxResource.java:254)
        at org.semanticwb.portal.api.GenericResource.render(GenericResource.java:124)
        at org.apache.jsp.swbadmin.jsp.editResource_jsp._jspService(editResource_jsp.java:152)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
        ... 38 more

**Comment by haxdai** [comment]
Caused by SemanticWebBuilder/SWB#71

**Comment by jordivs** [comment]
Resolved by SemanticWebBuilder/SWB#71
