### ISSUE TITLE
SWBDocumenter no publica versión de la documentación del proceso

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBP#27]
Al publicar una versión de la documentación del proceso se genera un error 500 se despliega el detalle del error.

Se probo en los navegadores de Firefox y GoogleChrome

SystemId Unknown; Line #103; Column #158; java.lang.NullPointerException
2017-08-23 18:29:55,014 ERROR -
java.lang.NullPointerException
        at org.apache.xml.serializer.TreeWalker.dispatachChars(TreeWalker.java:246)
        at org.apache.xml.serializer.TreeWalker.startNode(TreeWalker.java:416)
        at org.apache.xml.serializer.TreeWalker.traverse(TreeWalker.java:145)
        at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:390)
        at org.semanticwb.process.documentation.resources.SWPDocumentationResource.processAction(SWPDocumentationResource.java:474)
        at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.java:376)
        at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.java:101)
        at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:392)
        at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:319)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1368)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
2017-08-23 18:29:55,014 ERROR - Attempt to process an HTTP-500: /es/demo/DocumentationManager/_aid/134/_mto/3/_act/a_sver/_mod/m_nver - 500:No es posible procesar el requerimiento:/es/demo/DocumentationManager/_aid/134/_mto/3/_act/a_sver/_mod/m_nver<br/>java.lang.NullPointerException

**Comment by haxdai** [comment]
Lo del comentario parece un issue aparte @jordivs

**Comment by jordivs** [comment]
**Reproducir incidencia**

**Precondiciones**

1.- La instancia cuenta con una plantilla para la documentación del proceso "Solicitud de Vacaciones#
2.- La plantilla cuenta con al menos 3 secciones

**Flujo inicial**
1.- En la sección de "Documentación" del sitio de Demo hacer clic en el proceso "Demo".
2.- Seleccionar el botón de "Editar"
3.- Editar las secciones con información por default.
4.- Seleccionar el botón de "Publicar Versión"
5.- En la ventana "Guardar Versión" Definir un comentario y hacer clic en el botón de "Guardar"

**Resultado**

La ventana de "Guardar Versión" no realiza la acción y genera la traza que se pegó la descripción principal. 
Y al dar clic en el botón de “cancelar" de la ventana y visualizar la "Versiones publicadas" se muestra el listado como si se hubieran publicado y sucede lo que se describe en el comentario
